Repository lanl/BEE, pull requests merged in 2023-05, with the labels that each got.

#679 Allow Absolute/Relative Paths for Main CWL and YAML Files
  beeflow/client/bee_client.py
  docs/sphinx/commands.rst
  docs/sphinx/examples.rst
  docs/sphinx/wf_api.rst
Labels: enhancement

#691 Update Charliecloud required in documentation
  docs/README.md
  docs/sphinx/installation.rst
Labels: lint-only

#692 Update version to 0.1.4 for release
  RELEASE.rst
  pyproject.toml
Labels: lint-only

#693 Minor edit to Release procedure
  RELEASE.rst
Labels: no ci
