Repository lanl/BEE, pull requests merged in 2025-03, with the labels that each got.

#1015 Add --remote flag to beeflow core start
  beeflow/client/core.py
  beeflow/common/config_driver.py
  docs/sphinx/commands.rst
Labels: enhancement

#1013 Add `__init__.py` files for `pytest-cov` discovery
  beeflow/__init__.py
  beeflow/client/__init__.py
  beeflow/common/__init__.py
  beeflow/common/build/__init__.py
  beeflow/common/crt/__init__.py
  beeflow/common/cwl/__init__.py
  beeflow/common/db/__init__.py
  beeflow/common/deps/__init__.py
  beeflow/common/gdb/__init__.py
  beeflow/common/integration/__init__.py
  beeflow/remote/__init__.py
  beeflow/scheduler/__init__.py
  beeflow/task_manager/__init__.py
  beeflow/wf_manager/__init__.py
  beeflow/wf_manager/resources/__init__.py
  coverage.svg
Labels: testing

#1010 Add job_limits to config; limit the number jobs in the job queue
  beeflow/common/build_interfaces.py
  beeflow/common/config_driver.py
  beeflow/task_manager/background.py
  beeflow/wf_manager/resources/wf_utils.py
  beeflow/wf_manager/wf_manager.py
Labels: enhancement

#1008 Prevent simultaneous task failures multiple archive calls
  beeflow/common/gdb/gdb_driver.py
  beeflow/common/gdb/neo4j_cypher.py
  beeflow/common/gdb/neo4j_driver.py
  beeflow/data/cwl/bee_workflows/cgt-2branches/README.txt
  beeflow/data/cwl/bee_workflows/cgt-2branches/cat.cwl
  beeflow/data/cwl/bee_workflows/cgt-2branches/cat2.cwl
  beeflow/data/cwl/bee_workflows/cgt-2branches/grep0.cwl
  beeflow/data/cwl/bee_workflows/cgt-2branches/grep1.cwl
  beeflow/data/cwl/bee_workflows/cgt-2branches/grep2.cwl
  beeflow/data/cwl/bee_workflows/cgt-2branches/grep3.cwl
  beeflow/data/cwl/bee_workflows/cgt-2branches/input.yml
  beeflow/data/cwl/bee_workflows/cgt-2branches/lorem.txt
  beeflow/data/cwl/bee_workflows/cgt-2branches/tar.cwl
  beeflow/data/cwl/bee_workflows/cgt-2branches/tar2.cwl
  beeflow/data/cwl/bee_workflows/cgt-2branches/workflow.cwl
  beeflow/tests/test_neo4j_cypher.py
  beeflow/tests/test_wf_update.py
  beeflow/wf_manager/resources/wf_update.py
  coverage.svg
Labels: bug

#1033 BUILD_FAIL should cause DEP_FAIL for dependent tasks
  beeflow/tests/test_wf_update.py
  beeflow/wf_manager/resources/wf_update.py
Labels: bug, builder
